{
 "title": "Solar",
 "description": "solar energy ",
 "time": { "from": "now/d + 7h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "SP power",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "mpptcharger_solarpanel_watts{job=\"arduino\"}",
     "legendFormat": "Watt"
    }
   ]
  },
  {
   "title": "Battery power",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "mpptcharger_batterycharge_amperes{job=\"arduino\"} * mpptcharger_batterycharge_volts{job=\"arduino\"}",
     "legendFormat": "Watt"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "mpptcharger_temp_celsius{job=\"arduino\", place=\"external\"}",
     "legendFormat": "external"
    },
    {
     "expr": "mpptcharger_temp_celsius{job=\"arduino\", place=\"inner\"}",
     "legendFormat": "internal"
    }
   ]
  },
  {
   "title": "SP voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "mpptcharger_solarpanel_volts{job=\"arduino\"}",
     "legendFormat": "Volatage"
    }
   ]
  },
  {
   "title": "Battery volts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "mpptcharger_batterycharge_volts{job=\"arduino\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Produced",
   "type": "gauge",
   "description": "Produced for period of checked time",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(mpptcharger_solarpanel_watts{job=\"arduino\"}[$__range]) * ${__range_s} / 3600000",
     "legendFormat": "kwt/h"
    }
   ]
  },
  {
   "title": "SP current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "mpptcharger_solarpanel_amperes{job=\"arduino\"}",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Battery current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "mpptcharger_batterycharge_amperes{job=\"arduino\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Generated power by hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(mpptcharger_solarpanel_watts{job=\"arduino\"}[1h]) / 1000",
     "legendFormat": "generated"
    }
   ]
  }
 ]
}